# Generated by Django 5.2.1 on 2025-05-31 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')])),
                ('descripcion', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(5, message='La descripción debe tener al menos 5 caracteres.'), django.core.validators.MaxLengthValidator(10, message='La descripción no debe superar los 10 caracteres.')])),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El stock debe ser mayor a 0.')])),
            ],
        ),
    ]
